[tool.poetry]
name = "vocalistencast"
version = "0.1.0"
description = ""
authors = ["Kasai Kou"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gradio = "^3.50.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
